[package]
name = "opcos"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
axum.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
async-trait.workspace = true
keyring.workspace = true
rusqlite.workspace = true
reqwest.workspace = true
tokio.workspace = true
futures-util.workspace = true
tokio-tungstenite.workspace = true
notify.workspace = true
getrandom.workspace = true
subtle.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
opcos-engine = { path = "../crates/opcos-engine" }
opcos-hosts = { path = "../crates/opcos-hosts" }
opcos-assets = { path = "../crates/opcos-assets" }
serde_yaml.workspace = true
sha2.workspace = true
opcos-policy = { path = "../crates/opcos-policy" }
opcos-provider = { path = "../crates/opcos-provider" }
opcos-rvm = { path = "../crates/opcos-rvm" }
opcos-mcp = { path = "../crates/opcos-mcp" }
opcos-store = { path = "../crates/opcos-store" }
opcos-cloud-broker = { path = "../crates/opcos-cloud-broker" }
url.workspace = true
