[package]
name = "opcos-engine"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
futures-util.workspace = true
opcos-policy = { path = "../opcos-policy" }
opcos-provider = { path = "../opcos-provider" }
opcos-hosts = { path = "../opcos-hosts" }
opcos-store = { path = "../opcos-store" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
opcos-rvm = { path = "../opcos-rvm" }
url.workspace = true
