[package]
name = "opcos-assets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
url.workspace = true
opcos-rvm = { path = "../opcos-rvm" }
